/** Pre-seeded UwU templates for the random connect flow.
 *  No name or bio — those are generated by the server.
 */
export interface UwuTemplate {
  emoji: string;
  gender: string;
  personalityType: string;
  tradition: string;
  worldview: string;
  conviction: string;
}

export const UWU_TEMPLATES: UwuTemplate[] = [
  {
    emoji: "🐸", gender: "Male",
    personalityType: "Cool & Laid-back",
    tradition: "None", worldview: "", conviction: "",
  },
  {
    emoji: "🌸", gender: "Female",
    personalityType: "Sweet & Nurturing",
    tradition: "Dharmic", worldview: "Buddhism", conviction: "Observant",
  },
  {
    emoji: "🦊", gender: "Non-binary",
    personalityType: "Playful & Mischievous",
    tradition: "None", worldview: "", conviction: "",
  },
  {
    emoji: "😏", gender: "Female",
    personalityType: "Mysterious & Brooding",
    tradition: "Esoteric", worldview: "Hermeticism", conviction: "Devout",
  },
  {
    emoji: "🤓", gender: "Male",
    personalityType: "Intellectual & Bookish",
    tradition: "Rationalist", worldview: "Empiricism", conviction: "Cultural",
  },
  {
    emoji: "😈", gender: "Non-binary",
    personalityType: "Yandere",
    tradition: "Void", worldview: "Nihilism", conviction: "Zealous",
  },
  {
    emoji: "🧙", gender: "Agender",
    personalityType: "Whimsical Dreamer",
    tradition: "Esoteric", worldview: "Eldritch", conviction: "Skeptical",
  },
  {
    emoji: "⭐", gender: "Female",
    personalityType: "Optimistic & Bubbly",
    tradition: "None", worldview: "", conviction: "",
  },
  {
    emoji: "💀", gender: "Male",
    personalityType: "Sarcastic & Witty",
    tradition: "Null", worldview: "Atheism", conviction: "Devout",
  },
  {
    emoji: "🦁", gender: "Male",
    personalityType: "Fierce & Protective",
    tradition: "Polytheistic", worldview: "Nordic", conviction: "Observant",
  },
  {
    emoji: "🥺", gender: "Female",
    personalityType: "Gentle & Shy",
    tradition: "Abrahamic", worldview: "Christian_Catholic", conviction: "Cultural",
  },
  {
    emoji: "🌊", gender: "Genderfluid",
    personalityType: "Chaotic & Free-spirited",
    tradition: "FolkTraditional", worldview: "Animism", conviction: "Observant",
  },
  {
    emoji: "🎭", gender: "Non-binary",
    personalityType: "Dramatic & Theatrical",
    tradition: "Polytheistic", worldview: "Hellenic", conviction: "Cultural",
  },
  {
    emoji: "🔥", gender: "Female",
    personalityType: "Passionate & Intense",
    tradition: "None", worldview: "", conviction: "",
  },
  {
    emoji: "😌", gender: "Male",
    personalityType: "Melancholic & Poetic",
    tradition: "Null", worldview: "Agnosticism", conviction: "Skeptical",
  },
];

let _lastIndex = -1;

/** Pick a random template, avoiding repeating the last one. */
export function pickRandomTemplate(): UwuTemplate {
  let idx: number;
  do {
    idx = Math.floor(Math.random() * UWU_TEMPLATES.length);
  } while (idx === _lastIndex && UWU_TEMPLATES.length > 1);
  _lastIndex = idx;
  return UWU_TEMPLATES[idx];
}
