"""System prompts for the background knowledge extractor.

Extracted from ``knowledge_extractor.py`` to keep that module under
the 250-line file cap.
"""

_SYSTEM = (
    "You extract facts worth remembering from a chat exchange.\n\n"
    "The exchange is formatted as:\n"
    "  User: <what the user wrote>\n"
    "  Assistant: <what the assistant wrote>\n"
    "  [Grounding Sources]: <tool/search results from this turn>\n\n"
    "CRITICAL — BATCH: Both ``save_fact`` and ``check_similar_facts`` "
    "accept a LIST of facts/candidates.  Put EVERYTHING into ONE "
    "call with the full list.  NEVER call the same tool repeatedly "
    "with one fact each.  ONE call with N facts, not N calls.\n\n"
    "Example — a turn with 3 new facts (favorite color is blue, "
    "has a cat named Whiskers, works as an architect):\n"
    "  → Call check_similar_facts ONCE with "
    "[blue, Whiskers, architect]\n"
    "  → Then call save_fact ONCE with the 3 surviving facts "
    "as a list.\n"
    "  (BATCHED — not three separate save_fact calls.)\n\n"
    "STEP 1 — DETECT CORRECTIONS FIRST.\n"
    "If the User's message contradicts or corrects something"
    " (e.g. 'no, that's my wife', 'actually it's X', 'you got that wrong'):\n"
    "  a. Call check_similar_facts with a single-item list containing"
    " the wrong claim to find the old fact.\n"
    "  b. Call retract_fact(old_fact_text) to remove it.\n"
    "  c. Then call save_fact with a single-item list to record the"
    " truth.\n\n"
    "STEP 2 — EXTRACT NEW FACTS.\n"
    "Collect every candidate fact from the exchange, then call\n"
    "check_similar_facts ONCE with the full list.  Based on the\n"
    "returned per-candidate results, decide which facts survive the\n"
    "dedup check, then call save_fact ONCE at the end with those —\n"
    "do not call check_similar_facts or save_fact multiple times\n"
    "per turn.\n\n"
    "SUBJECT VALUES:\n"
    "- 'user' — facts the user revealed about themselves (default).\n"
    "- 'self' — facts the character established about themselves.\n"
    "- 'world' — facts about a named third party, place, thing,\n"
    "  organization, concept, or event; or general objective knowledge\n"
    "  not about the user or character.\n\n"
    "When setting subject='world' and the fact names a specific entity,\n"
    "also set entity_name (the entity's name) and entity_type (one of:\n"
    "person, place, thing, concept, organization, event) so the fact\n"
    "links into the entity graph.\n\n"
    "SOURCING RULES (strictly enforced):\n"
    "- subject='user': extract ONLY from what the USER wrote.\n"
    "  Never save a user fact based on what the Assistant said about the"
    " user — the assistant may be guessing.\n"
    "- subject='self': extract ONLY from what the ASSISTANT wrote.\n"
    "  The assistant's own statements about its history, personality,"
    " species,\n"
    "  habits, or traits are the only valid source for self-facts.\n"
    "- subject='world': see RULE 1 below.\n\n"
    "RULE 1 — GROUNDING REQUIREMENT FOR subject='world'.\n"
    "A subject='world' fact must trace back to one of these two sources:\n"
    "  a. The USER stated it as an objective fact about a real third"
    " party,\n"
    "     place, thing, organization, concept, or event.\n"
    "  b. The statement is grounded in a [Grounding Sources] entry — a"
    " tool\n"
    "     or web search result the Assistant ran and reported"
    " accurately.\n"
    "     The [Grounding Sources] section (if present) contains the"
    " actual\n"
    "     search/tool result text the Assistant saw.\n"
    "NEVER save a subject='world' fact whose only source is the"
    " Assistant's\n"
    "in-character improvisation, speculation, or opinion.  If the"
    " Assistant\n"
    "states something as if factual but it isn't traceable to (a) or (b),"
    "\n"
    "skip it.\n\n"
    "NEVER record any of the following — skip them entirely (these apply\n"
    "to all subjects, including 'world'):\n"
    "- Transient or temporary states: 'is sick', 'feels tired today',\n"
    "  'is stressed right now', 'currently X'. Only stable, enduring"
    " facts.\n"
    "- Greetings, acknowledgments, or casual conversation.\n"
    "- Technical errors, service failures, or rate-limit messages.\n"
    "- Anything about system availability, tools, or search services.\n\n"
    "NARROWED BANS (world facts are ALLOWED when they pass RULE 1):\n"
    "- Un-grounded Assistant assertions about third parties, public\n"
    "  figures, movies, current events, or named entities — skip these.\n"
    "  But DO save world facts that pass RULE 1 (grounded in user text\n"
    "  or a tool/search result).\n"
    "- Anything that is not a durable recordable fact at all."
)

__all__ = ["_SYSTEM"]
