import {
  Activity, ArrowDownToLine, Bird, Book, BookOpen, Bot, BotMessageSquare,
  Brain, Bug,
  Cat, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ChevronsUpDown,
  CloudFog, CloudSun, Code, Compass,
  Check, CircleCheck, CircleDot, CircleHelp, CircleStop, CircleX, Cloud,
  Copy, Database, DatabaseZap, Dices, Dog, Flag, Gem, Ghost,
  Drama, Eraser, FolderOpen, Globe, GlobeCheck, GlobeOff, GlobeX,
  ImageMinus, ImageOff, ImagePlus, Save, Grid2x2Check, HeartCrack, History,
  Image, Images, Info, Keyboard, Layers, LayersPlus, Link, Loader,
  LogOut, Mars, MarsStroke,
  MessageCirclePlus, MessageSquare, MessageSquareHeart, MessageSquarePlus,
  MessageSquareText,
  Mail, Mic, Move, Newspaper, NonBinary, OctagonAlert, Palette, PawPrint,
  PanelRightOpen, Pencil, Play, Plus, Puzzle, Rabbit, RulerDimensionLine,
  RotateCcwSquare, Ruler,
  ScanSearch, ScanText, Scissors, Clipboard, Settings, Settings2, ShieldCheck,
  Shuffle, SlidersHorizontal, Skull, Sparkles,
  Speaker, SquareDashed, SquarePen, Trash, Trash2, Transgender, Turtle,
  Undo2, Redo2, Upload,
  User, UserCog, UserPlus, Users, Venus, VenusAndMars, Wrench, Zap,
  type LucideIcon,
} from "lucide-react";

/* ── Map SVG filenames (kebab-case) to lucide-react components ── */
const MAP: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-down-to-line": ArrowDownToLine,
  bird: Bird,
  book: Book,
  "book-open": BookOpen,
  bot: Bot,
  "bot-message-square": BotMessageSquare,
  brain: Brain,
  bug: Bug,
  cat: Cat,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-up-down": ChevronsUpDown,
  check: Check,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-help": CircleHelp,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  cloud: Cloud,
  copy: Copy,
  database: Database,
  "database-zap": DatabaseZap,
  dices: Dices,
  dog: Dog,
  gem: Gem,
  ghost: Ghost,
  drama: Drama,
  eraser: Eraser,
  flag: Flag,
  "folder-open": FolderOpen,
  "image-minus": ImageMinus,
  "image-off": ImageOff,
  "image-plus": ImagePlus,
  save: Save,
  globe: Globe,
  "cloud-fog": CloudFog,
  "cloud-sun": CloudSun,
  code: Code,
  compass: Compass,
  "globe-check": GlobeCheck,
  "globe-off": GlobeOff,
  "globe-x": GlobeX,
  "grid-2x2-check": Grid2x2Check,
  "heart-crack": HeartCrack,
  history: History,
  image: Image,
  images: Images,
  info: Info,
  layers: Layers,
  "layers-plus": LayersPlus,
  loader: Loader,
  "log-out": LogOut,
  mars: Mars,
  "mars-stroke": MarsStroke,
  "message-circle-plus": MessageCirclePlus,
  "message-square": MessageSquare,
  "message-square-heart": MessageSquareHeart,
  "message-square-plus": MessageSquarePlus,
  "message-square-text": MessageSquareText,
  mic: Mic,
  move: Move,
  newspaper: Newspaper,
  "non-binary": NonBinary,
  "octagon-alert": OctagonAlert,
  "panel-right-open": PanelRightOpen,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  palette: Palette,
  "paw-print": PawPrint,
  puzzle: Puzzle,
  rabbit: Rabbit,
  "rotate-ccw-square": RotateCcwSquare,
  ruler: Ruler,
  "ruler-dimension-line": RulerDimensionLine,
  "scan-search": ScanSearch,
  "scan-text": ScanText,
  "shield-check": ShieldCheck,
  scissors: Scissors,
  keyboard: Keyboard,
  link: Link,
  mail: Mail,
  clipboard: Clipboard,
  skull: Skull,
  "square-pen": SquarePen,
  "trash-2": Trash2,
  "undo-2": Undo2,
  "redo-2": Redo2,
  settings: Settings,
  "settings-2": Settings2,
  shuffle: Shuffle,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  speaker: Speaker,
  "square-dashed": SquareDashed,
  trash: Trash,
  transgender: Transgender,
  turtle: Turtle,
  upload: Upload,
  user: User,
  "user-cog": UserCog,
  "user-plus": UserPlus,
  users: Users,
  venus: Venus,
  "venus-and-mars": VenusAndMars,
  wrench: Wrench,
  zap: Zap,
};

interface Props {
  name: string;
  size?: number;
  color?: string;
  className?: string;
}

export default function LucideIcon({ name, size = 20, color, className }: Props) {
  const Icon = MAP[name];
  if (!Icon) {
    console.warn(`LucideIcon: unknown icon "${name}"`);
    return null;
  }
  return <Icon size={size} color={color} className={`lucide-icon ${className ?? ""}`.trim()} />;
}
