/**
 * UwUchat — Terms of Service page (/terms).
 * Last updated: 2026-06-15
 */

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { PublicShell } from "../layout/PublicShell";

const EFFECTIVE_DATE = "June 17, 2026";

const TOS_CONTENT = `
# Terms of Service

**Effective date:** ${EFFECTIVE_DATE}
**Last updated:** ${EFFECTIVE_DATE}

These Terms of Service ("Terms") govern your access to and use of UwUchat,
operated by Capsize LLC, a Colorado limited liability company ("we," "us," or
"our"). By creating an account and using UwUchat, you agree to be bound by
these Terms. If you do not agree, do not use UwUchat.

---

## 1. Age Restriction

UwUchat is strictly for users who are **18 years of age or older**. By
creating an account and completing the sign-up agreement, you confirm that you
meet this requirement. We reserve the right to terminate accounts if we have
reasonable cause to believe a user is under 18.

While we do not require government-issued ID verification, we rely on your
payment card and your explicit sign-up acknowledgement as confirmation of your
age. Providing false information about your age is a violation of these Terms
and may result in immediate account termination and reporting to relevant
authorities where required by law.

---

## 2. Entertainment Purposes Only

UwUchat is an **entertainment platform**. The AI characters you interact with
are fictional and do not represent real people or licensed professionals.
Nothing communicated by any character on this platform constitutes medical,
legal, financial, psychological, or any other form of professional advice.

Do not rely on character responses for real-world decisions. Always consult a
qualified professional for matters affecting your health, finances, or legal
situation.

---

## 3. AI Character Disclosure

All characters on UwUchat are generated by **artificial intelligence**. They
may be designed to simulate realistic conversation, but they are not real
people. They do not have genuine emotions, independent memories, or awareness
outside of what the platform explicitly provides.

The AI nature of all characters is disclosed at account creation and made
apparent through the platform's design and branding. This satisfies applicable
disclosure requirements, including the EU AI Act (Regulation 2024/1689,
Article 50) and comparable requirements in other jurisdictions.

---

## 4. Prohibited Content and Conduct

Users may not create, use, share, or solicit:

- Sexual or romantic content involving anyone described as, or who could
  reasonably be interpreted as, under 18 years of age, in any form. This is a
  zero-tolerance policy and will be reported to the National Center for Missing
  and Exploited Children (NCMEC) and law enforcement as required by 18 U.S.C.
  § 2258A.
- Content impersonating licensed medical, mental health, legal, or financial
  professionals in a manner that could be mistaken for genuine professional
  advice.
- Content targeting, harassing, threatening, or defaming specific identifiable
  real-world individuals.
- Instructions for creating weapons, explosives, dangerous biological or
  chemical agents, or other harmful items.
- Attempting to circumvent platform safety systems, including prompt injection,
  jailbreaking, or any technique designed to override content policies.
- Using automated access (bots, scrapers) without our prior written consent.

Violations may result in immediate account suspension or termination and may be
reported to relevant law enforcement authorities.

---

## 5. User-Generated Characters and Content

You are responsible for every character and piece of content you create or
upload (including profile pictures, banners, and character assets). By
submitting content, you represent and warrant that it complies with these Terms
and that you own or have the necessary rights to submit it.

You grant Capsize LLC a non-exclusive, worldwide, royalty-free license to host,
store, transmit, display, and operate your content solely for the purpose of
providing the UwUchat service. We do not claim ownership of your content; this
license terminates when your account is deleted and your data is purged. Chat
histories belonging to other users that reference your characters are governed
by those users' own data and are not affected by your account deletion.

Capsize LLC is not liable for character behavior that falls within these Terms,
but we reserve the right to remove any character or content that violates them,
at our sole discretion, with or without notice.

---

## 6. Platform Moderation

We reserve the right to remove content, suspend, or permanently terminate
accounts that violate these Terms, at our sole discretion and without advance
notice. Decisions about moderation are final.

We provide community reporting tools. Use them responsibly. False reports
submitted to harm other users may themselves result in account action.

---

## 7. Account Security

You are responsible for maintaining the confidentiality of your account
credentials and for all activity that occurs under your account. You agree to
notify us immediately at contact@uwuchat.com if you become aware of any
unauthorized access to or use of your account. We are not liable for any loss
or damage arising from your failure to safeguard your credentials.

---

## 8. Crisis Resources

If a conversation touches on themes of self-harm, suicide, or serious
emotional distress, UwUchat will display crisis resources. These resources
are provided for user safety and are not part of the AI character's response.

**If you are in crisis, please reach out:**
- **988 Suicide & Crisis Lifeline:** Call or text **988** (US)
- **Crisis Text Line:** Text HOME to **741741** (US)
- **International Association for Suicide Prevention:** https://www.iasp.info/resources/Crisis_Centres/

---

## 9. Payments and Subscriptions

### Plans

| Plan | Price | Messages per month |
|---|---|---|
| Lite | $10.00 / month | 200 |
| Companion | $15.00 / month | 400 |
| Connection | $25.00 / month | 800 |
| Devoted | $40.00 / month | 1,500 |

### Automatic Renewal

**All plans automatically renew monthly.** Your payment method on file will be
charged the applicable plan price on the same date each month until you cancel.
By subscribing, you authorize us to charge your payment method on a recurring
monthly basis. You will receive a receipt by email after each charge.

### Cancellation

You may cancel at any time from your account settings or by contacting us at
contact@uwuchat.com. Cancellation takes effect at the end of your current
billing period. You retain full access through the end of the period for which
you have paid; no partial refunds are issued for unused days.

### Price Changes

We reserve the right to change pricing with 30 days' notice sent to your
registered email address. Continued use after the new price takes effect
constitutes your acceptance of the updated pricing.

### Refund Policy

All fees are non-refundable except as required by applicable law.

**EU / UK Users:** If you are located in the European Union or United Kingdom,
you have a statutory 14-day right of withdrawal from the date of purchase. **By
activating your UwUchat subscription and beginning to use the service, you
expressly request immediate performance of the service and acknowledge that your
right of withdrawal is waived once service delivery has begun**, in accordance
with Article 16(m) of Directive 2011/83/EU and equivalent UK provisions.

---

## 10. Intellectual Property

The UwUchat platform, including all software, design, trademarks, and
non-user-generated content, is owned by Capsize LLC and protected by applicable
intellectual property laws. You may not copy, modify, distribute, or create
derivative works of our platform without our express written consent.

---

## 11. Copyright / DMCA

We respect intellectual property rights and expect users to do the same. If
you believe that content on UwUchat infringes your copyright, you may submit a
notice under the Digital Millennium Copyright Act (17 U.S.C. § 512) to our
designated agent:

**Designated DMCA Agent:**
Joe Curlee — Capsize LLC
contact@uwuchat.com

Your notice must include: (1) identification of the copyrighted work claimed to
be infringed; (2) identification of the allegedly infringing material and
information sufficient to locate it on the service; (3) your contact
information; (4) a statement that you have a good-faith belief that the use is
not authorized by the copyright owner, its agent, or the law; (5) a statement,
under penalty of perjury, that the information in your notice is accurate and
that you are authorized to act on behalf of the copyright owner; and (6) your
physical or electronic signature.

We will respond to valid notices in accordance with 17 U.S.C. § 512 and will
terminate repeat infringers' accounts in appropriate circumstances.

---

## 12. Disclaimer of Warranties

UwUchat is provided "as is" and "as available" without warranties of any kind,
express or implied, including but not limited to merchantability, fitness for a
particular purpose, or non-infringement. We do not warrant that the service
will be uninterrupted, error-free, or free of harmful components.

---

## 13. Limitation of Liability

To the fullest extent permitted by applicable law, Capsize LLC and its members,
officers, employees, and agents shall not be liable for any indirect,
incidental, special, consequential, or punitive damages — including loss of
profits, data, or goodwill — arising from or related to your use of UwUchat,
even if we have been advised of the possibility of such damages. Our total
liability to you for all claims shall not exceed the greater of (a) the amounts
you paid us in the 12 months preceding the claim or (b) $100 USD.

Some jurisdictions do not allow the exclusion of certain warranties or
limitation of consequential damages. In such jurisdictions, the above
limitations apply to the maximum extent permitted by law.

---

## 14. Indemnification

You agree to defend, indemnify, and hold harmless Capsize LLC and its members,
officers, employees, and agents from and against any claims, liabilities,
damages, losses, and expenses (including reasonable attorneys' fees) arising
out of or in any way connected with: (a) your access to or use of UwUchat;
(b) your violation of these Terms; (c) any content you submit, post, or
transmit through the service; or (d) your violation of any third-party right,
including any intellectual property right or right of privacy.

---

## 15. Governing Law and Dispute Resolution

These Terms are governed by and construed in accordance with the laws of the
**State of Colorado**, without regard to conflict-of-law principles.

**Any dispute arising from these Terms or your use of UwUchat will be resolved
by binding individual arbitration** under the AAA Consumer Arbitration Rules,
rather than in court, except that either party may seek emergency injunctive
relief in a court of competent jurisdiction in Denver, Colorado. Filing fees
are governed by the AAA Consumer Arbitration Rules; we will pay all AAA fees
for claims under $75,000 unless the arbitrator finds the claim frivolous.

**YOU WAIVE ANY RIGHT TO A CLASS ACTION OR CLASS ARBITRATION.** You agree that
claims will be brought only in your individual capacity, not as a plaintiff or
class member in any purported class or representative proceeding.

**Arbitration Opt-Out:** You may opt out of binding arbitration by sending
written notice to contact@uwuchat.com with the subject line "Arbitration
Opt-Out" and your account email address within **30 days** of first agreeing to
these Terms. If you opt out, disputes will be resolved exclusively in state or
federal courts located in Denver, Colorado.

---

## 16. Colorado Consumer Protection

We comply with the Colorado Consumer Protection Act (C.R.S. § 6-1-101 et seq.)
and the Colorado Privacy Act (C.R.S. § 6-1-1301 et seq.). Colorado residents
have the rights described in our Privacy Policy.

---

## 17. Termination

**By you:** You may close your account at any time from your account settings.
Upon account closure, your data will be purged within 30 days in accordance
with our Privacy Policy. Active subscription access continues through the end
of the current billing period; no partial refunds are issued.

**By us:** We may suspend or terminate your account at any time for violation
of these Terms, with or without notice. Upon termination for cause, no refund
will be issued for any remaining subscription period.

**Survival:** Sections 4, 5, 10, 11, 12, 13, 14, 15, and 19 survive any
termination or expiration of these Terms.

---

## 18. Force Majeure

We are not liable for any delay or failure to perform resulting from causes
outside our reasonable control, including acts of God, natural disasters, war,
terrorism, infrastructure failures, cyberattacks, pandemic, or actions of
third-party service providers.

---

## 19. General Provisions

**Entire Agreement.** These Terms, together with our Privacy Policy, constitute
the entire agreement between you and Capsize LLC regarding UwUchat and supersede
all prior agreements and understandings.

**Severability.** If any provision of these Terms is found to be unenforceable,
that provision will be modified to the minimum extent necessary to make it
enforceable, and the remaining provisions will continue in full force and effect.

**Waiver.** Our failure to enforce any right or provision of these Terms will
not be considered a waiver of that right or provision.

**Assignment.** You may not assign your rights or obligations under these Terms
without our prior written consent. We may assign our rights freely, including
in connection with a merger, acquisition, or sale of assets.

**No Third-Party Beneficiaries.** These Terms do not create any third-party
beneficiary rights.

---

## 20. Changes to These Terms

We may revise these Terms at any time. When we make material changes, we will
notify you by email sent to your registered address or by a prominent in-app
notice at least 14 days before the changes take effect. Your continued use of
UwUchat after the effective date constitutes your acceptance of the revised Terms.

---

## 21. Contact

**Capsize LLC**
Colorado, United States

contact@uwuchat.com

---

*These Terms were last updated on ${EFFECTIVE_DATE}.*
`;

export default function TermsOfService() {
  return (
    <PublicShell>
      <div className="legal-page">
        <div className="legal-container">
          <div className="legal-content">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{TOS_CONTENT}</ReactMarkdown>
          </div>
        </div>
      </div>
    </PublicShell>
  );
}
